// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAf1Vm4Aj1Njx5JjgVYVj7ZC-iJI77918g',
    appId: '1:263062311326:web:8b741bc78f69b29706068f',
    messagingSenderId: '263062311326',
    projectId: 'mindmend-2',
    authDomain: 'mindmend-2.firebaseapp.com',
    storageBucket: 'mindmend-2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgn2mxCTNTOalqsRtuwx5KWu0T6wV8sKM',
    appId: '1:263062311326:android:e85ce78018a05e6406068f',
    messagingSenderId: '263062311326',
    projectId: 'mindmend-2',
    storageBucket: 'mindmend-2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDL1gH46u8USIVZW8y61324BHVbHWpM0D8',
    appId: '1:263062311326:ios:ca1e3f997f2b1ca106068f',
    messagingSenderId: '263062311326',
    projectId: 'mindmend-2',
    storageBucket: 'mindmend-2.firebasestorage.app',
    iosClientId: '263062311326-qn6eqeoirp4o3806cfgc13ma7er0jqsa.apps.googleusercontent.com',
    iosBundleId: 'com.mindmend.app',
  );

}